/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * compraGUI.java
 *
 * Created on 09/05/2012, 22:11:58
 */
package GUI;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.InitialContext;
import javax.swing.DefaultListModel;
import sistemarodoviario.*;


/**
 *
 * @author 30946220
 */
public class Compra extends javax.swing.JFrame {
    String escolha;
    /** Creates new form compraGUI */
    public Compra() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        lblOrigem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOrigem = new javax.swing.JList();
        lblDestino = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDestino = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        quantidadeTxt = new javax.swing.JTextField();
        radioIda = new javax.swing.JRadioButton();
        radioIdaVolta = new javax.swing.JRadioButton();
        btnProximo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Desenvolvido por Bruno, Camila e Felipe"));

        lblOrigem.setText("Origem :");

        try { InitialContext context = new InitialContext();//LISTA DE COISAS HEHEHE
            CidadeSessionBeanRemote bean = (CidadeSessionBeanRemote)context.lookup("ejb/Cidade");
            List<Object[]> resultado = bean.retornaCidade();
            DefaultListModel model = new DefaultListModel();
            listOrigem.setModel(model);
            for (Object[] objects : resultado) {
                String itemLista = objects[1].toString();
                model.addElement(itemLista);
            }

        } catch (Exception ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);}
        listOrigem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listOrigem);

        lblDestino.setText("Destino :");

        try { InitialContext context = new InitialContext();//LISTA DE COISAS HEHEHE
            CidadeSessionBeanRemote bean = (CidadeSessionBeanRemote)context.lookup("ejb/Cidade");
            List<Object[]> resultado = bean.retornaCidade();
            DefaultListModel model = new DefaultListModel();
            listDestino.setModel(model);
            for (Object[] objects : resultado) {
                String itemLista = objects[1].toString();
                model.addElement(itemLista);
            }

        } catch (Exception ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);}
        listDestino.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listDestino);

        jLabel3.setText("Quantidade :");

        radioIda.setText(" Ida");
        radioIda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIdaActionPerformed(evt);
            }
        });

        radioIdaVolta.setText("Ida e volta");
        radioIdaVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIdaVoltaActionPerformed(evt);
            }
        });

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblOrigem)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(quantidadeTxt)))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioIda)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(radioIdaVolta)
                            .addGap(28, 28, 28)
                            .addComponent(btnProximo))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrigem)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestino))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(quantidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProximo)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(radioIda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioIdaVolta)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioIdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIdaActionPerformed
        escolha = "Ida";
    }//GEN-LAST:event_radioIdaActionPerformed

    private void radioIdaVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIdaVoltaActionPerformed
        escolha = "Ida e Volta";
    }//GEN-LAST:event_radioIdaVoltaActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        EscolhaHorarios tela = new EscolhaHorarios(escolha, quantidadeTxt.getText(), listOrigem.getSelectedValue().toString(), listDestino.getSelectedValue().toString());
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProximoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new InicioGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Compra().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JList listDestino;
    private javax.swing.JList listOrigem;
    private javax.swing.JTextField quantidadeTxt;
    private javax.swing.JRadioButton radioIda;
    private javax.swing.JRadioButton radioIdaVolta;
    // End of variables declaration//GEN-END:variables
}
