/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.List;
import javax.naming.InitialContext;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sistemarodoviario.CidadeSessionBeanRemote;
import sistemarodoviario.LinhaSessionBeanRemote;
import sistemarodoviario.ParadaSessionBeanRemote;
import sistemarodoviario.jpa.Cidade;
import sistemarodoviario.jpa.Linha;
import sistemarodoviario.jpa.Parada;

/**
 *
 * @author Bruno
 */
public class CriarLinha2 extends javax.swing.JFrame {
    InitialContext context;
    List<Object[]> resultado;
    String cidadeOrigem;
    String cidadeDestino;
    Linha linhaIda;
    Linha linhaVolta;
    Parada parada;

    /**
     * Creates new form CriarLinha2
     */
    public CriarLinha2() {
        initComponents();
    }

    public CriarLinha2(String cidadeOrigem, String cidadeDestino) {
        this.cidadeOrigem = cidadeOrigem;
        this.cidadeDestino = cidadeDestino;        
        initComponents();
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        paradaList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        try {
            context = new InitialContext();
            CidadeSessionBeanRemote bean = (CidadeSessionBeanRemote)context.lookup("ejb/Cidade");
            resultado = bean.retornaCidades (cidadeOrigem, cidadeDestino);
            DefaultListModel model = new DefaultListModel();
            paradaList.setModel(model);
            for (Object[] objects : resultado) {
                String itemLista = objects[1].toString();
                model.addElement(itemLista);
            }
        } catch (Exception e) {}

        paradaList.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(paradaList);

        jLabel4.setText("Escolha as paradas da linha:");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /**try {
            InitialContext context = new InitialContext();
            Parada parada;
            LinhaSessionBeanRemote linhaBean = (LinhaSessionBeanRemote)context.lookup("ejb/Linha");
            ParadaSessionBeanRemote paradaBean = (ParadaSessionBeanRemote)context.lookup("ejb/Parada");
            CidadeSessionBeanRemote cidadeBean = (CidadeSessionBeanRemote)context.lookup("ejb/Cidade");
            Linha linhaIda, linhaVolta;
            linhaIda = linhaBean.retornaLinhaToda("São Paulo", "Campinas");            
            linhaVolta = linhaBean.retornaLinhaToda("Campinas", "São Paulo");
            Cidade cidade = cidadeBean.cidadePeloNome("Campinas");
            parada = new Parada (linhaIda, cidade);
            paradaBean.salvar(parada);
            cidade = cidadeBean.cidadePeloNome("São Paulo");
            parada = new Parada (linhaVolta, cidade);
            paradaBean.salvar(parada);
            //int[] itens = paradaList.getSelectedIndices();
            //for (int i = 0; i <= itens.length; i++) {
                //Object sel = paradaList.getModel().getElementAt(itens[i]);
                cidade = cidadeBean.cidadePeloNome("Jundiaí");
                parada = new Parada(linhaIda, cidade);
                paradaBean.salvar(parada);
                parada = new Parada(linhaVolta, cidade);
                paradaBean.salvar(parada);
            } catch (Exception e) {}**/
        try {
            context = new InitialContext();
            ParadaSessionBeanRemote paradaBean = (ParadaSessionBeanRemote)context.lookup("ejb/Parada");
            CidadeSessionBeanRemote cidadeBean = (CidadeSessionBeanRemote)context.lookup("ejb/Cidade");
            LinhaSessionBeanRemote linhaBean = (LinhaSessionBeanRemote)context.lookup("ejb/Linha");
            linhaIda = linhaBean.retornaLinhaToda(cidadeOrigem, cidadeDestino);
            linhaVolta = linhaBean.retornaLinhaToda(cidadeDestino, cidadeOrigem);
            Cidade cidade = cidadeBean.cidadePeloNome(cidadeDestino);
            parada = new Parada (linhaIda, cidade);
            paradaBean.salvar(parada);
            cidade = cidadeBean.cidadePeloNome(cidadeOrigem);
            parada = new Parada (linhaVolta, cidade);
            paradaBean.salvar(parada);
            int[] itens = paradaList.getSelectedIndices();
            if(itens.length > 0) {
            for (int i = 0; i <= itens.length; i++) {
                Object sel = paradaList.getModel().getElementAt(itens[i]);
                cidade = cidadeBean.cidadePeloNome(sel.toString());
                parada = new Parada(linhaIda, cidade);
                paradaBean.salvar(parada);
                parada = new Parada(linhaVolta, cidade);
                paradaBean.salvar(parada);
            }
            }             
        } catch (Exception e) {}
        JOptionPane.showMessageDialog(null, "Linha "+cidadeOrigem+" - "+cidadeDestino+" criada!");
             new Gerenciar().setVisible(true);
             this.dispose();       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CriarLinha().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarLinha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarLinha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarLinha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarLinha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CriarLinha2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList paradaList;
    // End of variables declaration//GEN-END:variables
}
