/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * onibusGUI.java
 *
 * Created on 09/05/2012, 22:04:13
 */
package GUI;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.InitialContext;
import sistemarodoviario.*;
import sistemarodoviario.jpa.*;

/**
 *
 * @author 30946220
 */
public class EscolhaHorarios extends javax.swing.JFrame {
    String idaVolta;
    String quantidadePassagens;
    String cidadeOrigem;
    String cidadeDestino;
    Linha linhaIda;
    Linha linhaVolta;
    List<Object[]> resultado;
    String data;
    String horario;

    /** Creates new form onibusGUI */
    public EscolhaHorarios() {
        initComponents();
    }
    
    public EscolhaHorarios (String idaVolta, String quantidadePassagens, String cidadeOrigem, String cidadeDestino) {
        this.idaVolta = idaVolta;
        this.quantidadePassagens = quantidadePassagens;
        this.cidadeOrigem = cidadeOrigem;
        this.cidadeDestino = cidadeDestino;
        try {
            InitialContext context = new InitialContext();
            LinhaSessionBeanRemote linhabean = (LinhaSessionBeanRemote)context.lookup("ejb/Linha");
            linhaIda = linhabean.retornaLinha(cidadeOrigem, cidadeDestino);
            linhaVolta = linhabean.retornaLinha(cidadeDestino, cidadeOrigem);
        } catch (Exception ex) {Logger.getLogger(EscolhaHorarios.class.getName()).log(Level.SEVERE, null, ex);}
        initComponents();
        if (idaVolta.equals("Ida")) {
            lblVolta.setVisible(false);
            comboVolta.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLinha = new javax.swing.JLabel();
        lblIda = new javax.swing.JLabel();
        lblVolta = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtLinha = new javax.swing.JTextField();
        txtLinha.setText("Linha "+linhaIda.getCidadeOrigem().getCidadeNome()+"-"+linhaIda.getCidadeDestino().getCidadeNome());
        txtQuantidade = new javax.swing.JTextField();
        proximo = new javax.swing.JButton();
        comboVolta = new javax.swing.JComboBox();
        comboIda = new javax.swing.JComboBox();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Desenvolvido por Buno, Camila e Felipe"));

        lblLinha.setText("Linha :");

        lblIda.setText("Datas/Horarios Ida:");

        lblVolta.setText("Datas/Horarios Volta:");

        lblQuantidade.setText("Quantidade de passagens :");

        txtLinha.setForeground(new java.awt.Color(0, 0, 255));
        txtLinha.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtLinha.setEnabled(false);

        txtQuantidade.setText(quantidadePassagens);
        txtQuantidade.setForeground(new java.awt.Color(0, 0, 255));
        txtQuantidade.setEnabled(false);

        proximo.setText("Próximo");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        try {
            InitialContext context = new InitialContext();
            LinhaSessionBeanRemote bean = (LinhaSessionBeanRemote) context.lookup("ejb/Linha");
            resultado = bean.retornaPorLinha(linhaVolta.getIdLinha());
            comboVolta.addItem("Selecione uma opção");
            for (Object[] objects : resultado) {
                comboVolta.addItem(objects[1] +"-"+objects[3]+ " Chegada Prevista: "+objects[2]);
            }
        } catch (Exception ex) { }

        try {
            InitialContext context = new InitialContext();
            LinhaSessionBeanRemote bean = (LinhaSessionBeanRemote) context.lookup("ejb/Linha");
            resultado = bean.retornaPorLinha(linhaIda.getIdLinha());
            comboIda.addItem("Escolha uma opção");
            for (Object[] objects : resultado) {
                comboIda.addItem(objects[1] +"-"+objects[3]+ " Chegada Prevista: "+objects[2]);
            }
        } catch (Exception ex) { }
        comboIda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIda)
                            .addComponent(lblVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboVolta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboIda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLinha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 185, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinha)
                    .addComponent(txtLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboIda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVolta)
                    .addComponent(comboVolta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(proximo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboIdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdaActionPerformed
        String s = comboIda.getSelectedItem().toString();
        data = s.substring(0, 10);
        horario = s.substring(s.indexOf("-")+1, s.indexOf(" "));
    }//GEN-LAST:event_comboIdaActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        EscolhaAssento tela = new EscolhaAssento(linhaIda,data,horario,quantidadePassagens,cidadeDestino);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_proximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EscolhaHorarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboIda;
    private javax.swing.JComboBox comboVolta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIda;
    private javax.swing.JLabel lblLinha;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblVolta;
    private javax.swing.JButton proximo;
    private javax.swing.JTextField txtLinha;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
