/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.List;
import javax.naming.InitialContext;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sistemarodoviario.AssentoSessionBeanRemote;
import sistemarodoviario.LinhaSessionBeanRemote;
import sistemarodoviario.jpa.DataHora;
import sistemarodoviario.jpa.Linha;

/**
 *
 * @author Bruno
 */
public class EscolhaAssento extends javax.swing.JFrame {
    Linha linha;
    DataHora dh;
    String data;
    String horario;
    String qtdPassagens;
    List <String> seleções;
    String parada;
    
    public EscolhaAssento(Linha linha, String data, String horario, String qtdPassagens, String parada) {
        this.linha = linha;
        this.data = data;
        this.horario = horario;
        this.qtdPassagens = qtdPassagens;
        this.parada = parada;
        initComponents();
    }

    /**
     * Creates new form EscolhaAssento
     */
    public EscolhaAssento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listAssento = new javax.swing.JList();
        labelViagem = new javax.swing.JLabel();
        labelDataHorario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botaoProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        try {
            InitialContext context = new InitialContext();
            LinhaSessionBeanRemote bean = (LinhaSessionBeanRemote) context.lookup("ejb/Linha");
            AssentoSessionBeanRemote assentobean = (AssentoSessionBeanRemote)context.lookup("ejb/Assento");
            dh = bean.retornaDataHora(linha, data, horario);
            List<Object[]> resultado = assentobean.retornaAssentos(linha, dh);
            DefaultListModel model = new DefaultListModel();
            listAssento.setModel(model);
            for (Object[] objects : resultado) {
                String itemLista = objects[2].toString();
                model.addElement(itemLista);
            }
        }

        catch (Exception e) {}
        jScrollPane1.setViewportView(listAssento);

        labelViagem.setText("Linha "+linha.getCidadeOrigem().getCidadeNome()+" - "+linha.getCidadeDestino().getCidadeNome());
        labelViagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelDataHorario.setText("Data da Viagem: "+data+" / Horário: "+horario);
        labelDataHorario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Escolha de Assento:");

        botaoProximo.setText("Próximo");
        botaoProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(149, 149, 149))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDataHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelViagem, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDataHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoProximo)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProximoActionPerformed
        seleções = listAssento.getSelectedValuesList();
        if (seleções.size() > Integer.parseInt(qtdPassagens) || seleções.size() < Integer.parseInt(qtdPassagens)) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione " + qtdPassagens + " assento(s).");
        } else {
            int[] itens = listAssento.getSelectedIndices();
            String assentos = "";
            for (int i = 0; i < itens.length; i++) {
                Object sel = listAssento.getModel().getElementAt(itens[i]);
                assentos = assentos + sel.toString()+" ";
                try {
                    InitialContext context = new InitialContext();
                    AssentoSessionBeanRemote bean = (AssentoSessionBeanRemote) context.lookup ("ejb/Assento");
                    bean.mudaAssento(linha, dh, sel.toString());
                } catch(Exception e) {}
            }            
            String l = linha.getCidadeOrigem().getCidadeNome()+" - "+linha.getCidadeDestino().getCidadeNome();
            new ConfirmaCliente(l, parada, linha.getPreco(),Integer.parseInt(qtdPassagens), assentos, data, horario, linha).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botaoProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EscolhaAssento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoProximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDataHorario;
    private javax.swing.JLabel labelViagem;
    private javax.swing.JList listAssento;
    // End of variables declaration//GEN-END:variables
}
