INSERT INTO FUNCIONARIO (NOME_FUNC, SENHA_FUNC, USUARIO_FUNC)
VALUES ('Calebe Biachini', 'mackenzie', 'calebe');

INSERT INTO ESTADO (NOME_ESTADO)
VALUES ('São Paulo');
INSERT INTO ESTADO (NOME_ESTADO)
VALUES ('Rio de Janeiro');
INSERT INTO ESTADO (NOME_ESTADO)
VALUES ('Minas Gerais');
INSERT INTO ESTADO (NOME_ESTADO)
VALUES ('Bahia');

insert into CIDADE (CIDADE_NOME, ESTADO_FK)
VALUES ('São Paulo', 1);
insert into CIDADE (CIDADE_NOME, ESTADO_FK)
VALUES ('Barueri', 1);
insert into CIDADE (CIDADE_NOME, ESTADO_FK)
VALUES ('Bauru', 1);

INSERT INTO LINHA (PRECO, CIDADE_DESTINO, CIDADE_ORIGEM)
VALUES (60, 3, 1);

INSERT INTO DATA_HORA (DATA, HORA_CHEGADA, HORA_PARTIDA, LINHA_FK)
VALUES ('25/05/2012', '16:00', '12:00', 1);
INSERT INTO DATA_HORA (DATA, HORA_CHEGADA, HORA_PARTIDA, LINHA_FK)
VALUES ('25/05/2012', '18:00', '14:00', 1);
INSERT INTO DATA_HORA (DATA, HORA_CHEGADA, HORA_PARTIDA, LINHA_FK)
VALUES ('25/05/2012', '20:00', '16:00', 1);
INSERT INTO DATA_HORA (DATA, HORA_CHEGADA, HORA_PARTIDA, LINHA_FK)
VALUES ('25/05/2012', '22:00', '18:00', 1);

INSERT INTO PARADA (CIDADE_FK, LINHA_FK)
VALUES (2, 1);
INSERT INTO PARADA (CIDADE_FK, LINHA_FK)
VALUES (3, 1);

INSERT INTO ONIBUS (LINHA_FK, DATA_HORA_FK)
VALUES (1,1);
INSERT INTO ONIBUS (LINHA_FK, DATA_HORA_FK)
VALUES (1,2);
INSERT INTO ONIBUS (LINHA_FK, DATA_HORA_FK)
VALUES (1,3);
INSERT INTO ONIBUS (LINHA_FK, DATA_HORA_FK)
VALUES (1,4);

INSERT INTO ASSENTO (DISPONIBILIDADE, NUMERO_ASSENTO, ONIBUS_FK)
VALUES (1,'1',1), (1,'2',1), (1,'3',1), (1,'4',1), (0,'5',1), (0,'6',1), (1,'7',1), (0,'8',1), (1,'9',1), (1,'10',1),
(0,'11',1), (1,'12',1), (0,'13',1), (1,'14',1), (0,'15',1), (1,'16',1), (0,'17',1), (1,'18',1), (0,'19',1), (0,'20',1);

UPDATE ASSENTO
SET DISPONIBILIDADE = 0 WHERE NUMERO_ASSENTO = '1';

UPDATE ASSENTO
SET ID_ASSENTO = 1 WHERE NUMERO_ASSENTO = '1';